### ISSUE TITLE
How to cite this package?

### ISSUE THREAD

**Issue by jonas-schulze** [JuliaLinearAlgebra/ArnoldiMethod.jl#115]
Do you have a preferred way how we should attribute your work if we used it in a publication?

**Comment by haampie** [comment]
Currently there is no official way to cite it. How is this typically done?

Maybe @NymanLauri is interested in this too :)

**Comment by NymanLauri** [comment]
> How is this typically done?

Short answer: by adding a [`CITATION.cff`](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file to the repository :) you can even create a DOI with Zenodo.

In any case, I don’t think I would qualify to be listed as an author, considering the current state of the project.

**Comment by haampie** [comment]
Thanks, the more you know 👍 

I'm happy to add you as the second author, you've written a fair share of it. No conditions / obligations ;p

**Comment by ViralBShah** [comment]
If we need to add committers to the repo here for contributors, we should do that too.
